# GET NODE IMAGE
FROM node:12.2-alpine

# SET DIRECTORY
WORKDIR /usr/app
ENV HOST 0.0.0.0

# INSTALL NODE-GYP DEPENDENCIES
RUN apk add python make g++ inotify-tools

# Installs latest Chromium (73) package.
RUN apk update && apk upgrade && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
  apk add --no-cache \
  chromium@edge=~73.0.3683.103 \
  nss@edge \
  freetype@edge \
  harfbuzz@edge \
  ttf-freefont@edge

COPY package.json .

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Add user so we don't need --no-sandbox.
# RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
#   && mkdir -p /home/pptruser/Downloads /app \
#   && chown -R pptruser:pptruser /home/pptruser \
#   && chown -R pptruser:pptruser /app

# # Run everything after as non-privileged user.
# USER pptruser

# COPY FILES AND INSTALL NODE DEPENDENCIES
RUN npm install --quiet
COPY . .
CMD [ "npm", "run", "dev" ]